# Player
DEFAULT_TIME_SEC = 5 * 60
INITIAL_PIECES = 9

# Cells
EMPTY = 0
WHITE = 1
BLACK = 2

# States
SETUP_WHITE_NORMAL = 0
SETUP_BLACK_NORMAL = 1
SETUP_WHITE_REMOVE = 2
SETUP_BLACK_REMOVE = 3
ENDGAME_WHITE_NORMAL = 4
ENDGAME_BLACK_NORMAL = 5
ENDGAME_WHITE_REMOVE = 6
ENDGAME_BLACK_REMOVE = 7
WHITE_WON = 8
BLACK_WON = 9

# Modes
ONE_PLAYER = 1
TWO_PLAYER = 2

# Board
TOTAL_CELLS = 24